server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

token:
  secret: user_token

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=POST
          filters:
            - AuthorizationHeaderFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/swagger-ui/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id : user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - AuthorizationHeaderFilter
#            - PreCustomFilter
#            - PostCustomFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=user-request, user-request-header1
#            - AddResponseHeader=user-response, user-response-header1


        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/book-service/**
          filters:
            - name: PreCustomFilter
            - name: PostCustomFilter
#            - name: LoggingFilter
              args:
                baseMessage: Hi ,
                preLogger: true
                postLogger: true
#            - AddRequestHeader=book-request, book-request-header1
#            - AddResponseHeader=book-response, book-response-header1
logging:
  level:
    com.example.apigateway: debug
