server:
  port: 8082

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mariadb://localhost:3306/book-service
    password: rnrdj123
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true

