server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rnrdj123
    url: jdbc:mariadb://localhost:3306/user-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    #instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
#    ip-address: 211.114.128.103
#    instance-id: ${eureka.instance.ip-address}
#    non-secure-port:

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

