server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: syseoz@gmail.com
    password: '{cipher}AQAyG5R7ablE280fSH1MRJPZjHqu8B6wF6Q8pWfNWUKrIfTtm4VK3t3pLC6YyAeEKDHSO0js/rNm0v+ZXh52Qo5/3dVRVmlS3UQC/skV2Xc89qH5NeYFSxS/Zp8ToOl4vQX2I5YDodShiYErQsQf3hP34YRkss+9VHEuU6FTXNY/+HF9KfPb1Ay91QiNTDt2DZ5X5YNWpKFuoqo/tIzK2P69jUtZZWYMgMIO0gbrYv3/QJTeM5xu5+/Pb3S/rvXi+dHPRBItucO0YAg3W1EMGnsDlofP+p8WVw5EyhCDEJYizz6pgHEC4TsaagqpcI99trcplajxMMiJ2/WAuI2qoFwjwJbQ3frQDltRpMKe98fOAsr+abipEu+jfdBTS+3Br5/GX7NVE5J9OcmY5K9TA4rx'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

    show-sql: true
    #defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  level:
    com.example.userservice: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh


#token:
#  secret: user_token
#  expiration_time: 43200000