server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password:
#    url: jdbc:mariadb://localhost:3306/user-service

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

    show-sql: true
    #defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  level:
    com.example.userservice: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh


#token:
#  secret: user_token
#  expiration_time: 43200000