server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/SUN/inf_ms/native-config-repo
        git:
          #uri: file:///C:/Users/SUN/inf_ms/spring-cloud-config
          uri: https://github.com/sunjuyoung/spring-cloud-config
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
